Repository Kelompok-3-Capstone-Alterra-2023/Frontend, pull requests merged in 2023-06, with the labels that each got.

#33 Updated Withdrawal Pages
  app/withdraw/(bank)/bank-form.jsx
  app/withdraw/(bank)/payment-confirm.jsx
  app/withdraw/page.jsx
  app/withdraw/payment-control.jsx
  components/ui/Sidebar.js
Labels: Bug FIxes, Pages

#37 Pagination Alt and Admin Edit Article Pages
  app/admin-article-tables/page.jsx
  components/ui/PaginationAlt.js
Labels: Components, Pages

#69 Admin Article and Homepage Doctor list API Integrations
  api/all-doctor.js
  api/article-admin.js
  api/article.js
  api/awslink.js
  app/dashboard-admin/admin-article-tables/page.jsx
  app/dashboard-dokter/withdraw/(vwallet)/vwallet-form.jsx
  app/dashboard-dokter/withdraw/error.jsx
  app/dashboard-dokter/withdraw/page.jsx
  app/dashboard-dokter/withdraw/success/bank/page.jsx
  app/dashboard-dokter/withdraw/success/ewallet/page.jsx
  app/dashboard-dokter/withdraw/success/page.jsx
  app/dashboard-dokter/withdraw/withdraw-method-control-old.jsx
  app/dashboard-dokter/withdraw/withdraw-method-control.jsx
  app/dashboard-dokter/withdraw/withdraw-steps.jsx
  app/dashboard-dokter/withdraw/withdraw-steps/(bank)/bank-finale.jsx
  app/dashboard-dokter/withdraw/withdraw-steps/(bank)/bank-form.jsx
  app/dashboard-dokter/withdraw/withdraw-steps/(vwallet)/vwallet-finale.jsx
  app/dashboard-dokter/withdraw/withdraw-steps/(vwallet)/vwallet-form.jsx
  app/dashboard-dokter/withdraw/withdraw-steps/WithdrawFinale.jsx
  app/dashboard-dokter/withdraw/withdraw-steps/WithdrawForm.jsx
  app/dokter/alldoctor.jsx
  app/dokter/doctor-container/skeletonloader.jsx
  app/dokter/doctorcontainer.jsx
  app/dokter/loading.jsx
  app/dokter/page.jsx
  components/atoms/useWithdrawal.js
  components/loading/DoctorCardSkeletonLoading.jsx
  components/ui/BankCard.js
  components/ui/BankCardList.js
  public/assets/images/bankimages.js
Labels: Bug FIxes, API

#80 Chat Integration
  api/awslink.js
  api/chat-history.js
  api/socket.js
  app/dashboard-dokter/chat/[userid]/action.jsx
  app/dashboard-dokter/chat/[userid]/chat.jsx
  app/dashboard-dokter/chat/[userid]/chatSidebar.jsx
  app/dashboard-dokter/chat/[userid]/page.jsx
  app/dashboard-dokter/chat/page.jsx
  app/dashboard-dokter/layout.jsx
  app/dokter/loading-old.jsx
  components/ui/DoctorNavbarLayout.js
  components/ui/SidebarDokter.js
  next.config.js
Labels: Components, API

#99 Fix All Doctor and add Loader State
  app/dokter/alldoctor.jsx
  app/dokter/doctorcontainer.jsx
  app/dokter/loadstate.jsx
Labels: Bug FIxes, Components

#103 fix:integrasi data dokter yang sudah terdaftar
  app/dashboard-admin/edit-pengguna/daftar-dokter/page.jsx
  app/dashboard-admin/edit-pengguna/page.jsx
Labels: API

#109 Integrate User Order and Chat
  api/chat-history.js
  app/dashboard-dokter/chat/[userid]/chat.jsx
  app/dashboard-dokter/chat/[userid]/page.jsx
  app/dashboard-dokter/chat/chatSidebar.jsx
  app/dashboard-dokter/chat/page.jsx
  components/ui/SidebarDokter.js
Labels: Bug FIxes, Enchantment, API

#88 Fix Admin Article Page
  app/article-preview/[id]/page.jsx
  app/dashboard-admin/admin-article-tables/page.jsx
Labels: Bug FIxes, Pages

#117 Fix Admin Article Table behaviour and add default fallback state for Doctor Card
  app/dashboard-admin/admin-article-tables/page.jsx
  app/error.js
  components/ui/DoctorCard.js
  public/assets/images/default-doctor-alt.png
  public/assets/images/default-doctor.png
Labels: Bug FIxes, Enchantment
